version: '2'

services:
  web:
    image: dockerdemos/lab-web
    ports: ["80"]
    networks: ["private"]

  words:
    image: dockerdemos/lab-words-dispatcher
    networks: ["private"]

  words-java:
    image: dockerdemos/lab-words-java
    networks: ["private"]

  mongo:
    image: mongo:3.3.15
    networks: ["private"]

networks:
  private:
